### PR TITLE
Add VR600 Support

### PR DESCRIPTION
**Pull request by GuyKh**
Solves #2

### CODE REVIEW

**Comment by GuyKh** [comment]
Don't merge yet.

As a script this works but I want to test it in HA

**Comment by ericpignet** [comment]
Thanks for the contribution!
I let you test in HA, let me know when it's ready!

**Comment by GuyKh** [comment]
@ericpignet 

```
2020-05-06 10:36:01 INFO (SyncWorker_19) [custom_components.tplink_router.device_tracker] Retrieving PublicKey...
2020-05-06 10:36:01 INFO (SyncWorker_19) [custom_components.tplink_router.device_tracker] Failed to get AuthTokens. Retrying in 3 secs.
2020-05-06 10:36:04 INFO (SyncWorker_19) [custom_components.tplink_router.device_tracker] Retrieving PublicKey...
2020-05-06 10:36:04 INFO (SyncWorker_19) [custom_components.tplink_router.device_tracker] Retrieving JSessionID...
2020-05-06 10:36:05 INFO (SyncWorker_19) [custom_components.tplink_router.device_tracker] Retrieving Token...
2020-05-06 10:36:05 INFO (SyncWorker_19) [custom_components.tplink_router.device_tracker] Loading wireless clients...`
```

Looks great!

**Comment by GuyKh** [comment]
@ericpignet on my end - yes.
Here and there I see that `192.168.1.1` times out - but that's not in the initialization step.
So I'm kinda comfortable with merging this

**Comment by GuyKh** [comment]
@ericpignet on my end - yes.
Here and there I see that `192.168.1.1` times out - but that's not in the initialization step.
So I'm kinda comfortable with merging this

**Comment by ericpignet** [comment]
There were a few formatting issues: inconsistent indentation (2 chars), trailing whitespaces, double new lines. But that's alright, I'm planning to do an update shortly to clean up the logging, I'll take the opportunity to reformat.
I'm merging your PR.
Thanks again!

**Comment by GuyKh** [comment]
@ericpignet - thanks for your notes.
For some reason I didn't see this when comitting, but I'll put extra attention to it.

Thanks again

**Pull request merged**
